In [13]:
vocabulary = ["cat", "dog", "car", "bus", "ran", "fast", "the", "and", "sat"]

# q1

- Suppose that the vocabulary is {cat, dog, car, bus, ran, fast, the, and, sat}. There are two document classes, namely animal and vehicle. The training dataset of a text classification model consists of only three sentences, which include “the dog ran fast”, “the cat sat” and “the car and the bus ran fast”. The first two sentences are labeled animal and the last sentence is labeled vehicle.

## q1_a Draw count-based vector representations of all three sentences using bag-of-word features

In [11]:
str1 = "the dog ran fast"
str2 = "the cat sat" 
str3 = "the car and the bus ran fast"

In [ ]:
# tmp
# def tokenize(text):
#     # Replace punctuation marks with space + punctuation
#     punctuation_pattern = r'([.,!?;:])'
#     text = re.sub(punctuation_pattern, r' \1', text)
#     print(text)
#     return text.split()

In [7]:
import re
?re.sub

Signature: re.sub(pattern, repl, string, count=0, flags=0)
Docstring:
Return the string obtained by replacing the leftmost
non-overlapping occurrences of the pattern in string by the
replacement repl.  repl can be either a string or a callable;
if a string, backslash escapes in it are processed.  If it is
a callable, it's passed the Match object and must return
a replacement string to be used.
File:      ~/packages/miniforge3/envs/nlp/lib/python3.10/re.py
Type:      function

In [41]:
import re
def tokenize(string):
    punctuation_pattern = r'([.,!?;:])'
    string = re.sub(pattern=punctuation_pattern, repl=' ', string=string)
    res = string.split()
    return res

In [42]:
print(tokenize(str1))

['the', 'dog', 'ran', 'fast']


In [53]:
def countString(string, vocabulary):
    string_dict = {}
    string_list = tokenize(string)
    # print(string_list)
    for word in vocabulary:
        if word in string_list:
            # print(word)
            if word in string_dict.keys():
                string_dict[word] += 1
            else:
                string_dict[word] = 1
        else: 
            string_dict[word] = 0
    return string_dict

In [60]:
print(vocabulary)
feature_list = []
for str in [str1, str2, str3]:
    print(str)
    str_dict = countString(string=str, vocabulary=vocabulary)
    feature_list.append(list(str_dict.values()))
    print(list(str_dict.values()))

['cat', 'dog', 'car', 'bus', 'ran', 'fast', 'the', 'and', 'sat']
the dog ran fast
[0, 1, 0, 0, 1, 1, 1, 0, 0]
the cat sat
[1, 0, 0, 0, 0, 0, 1, 0, 1]
the car and the bus ran fast
[0, 0, 1, 1, 1, 1, 1, 1, 0]


## q1_b  Manually cluster the training examples using 2-means.

In [67]:
import numpy as np
feature_array = np.array(feature_list)
print(feature_array)

[[0 1 0 0 1 1 1 0 0]
 [1 0 0 0 0 0 1 0 1]
 [0 0 1 1 1 1 1 1 0]]


In [121]:
# k-means clustering
import array
from turtle import distance
import numpy as np
for i in range(1, 3):
    print(i)
def kMeansClustering(feature_array, k=2, max_iteration = 100):
    # initiate centroid randomly
    centroid = feature_array[np.random.choice(feature_array.shape[0],
                                               k, replace=False)]
    print(feature_array)
    print(centroid)
    lables = []
    for i in range(max_iteration):
        # TODO here
        # calculate distance and assign cluster 
        distance = np.linalg.norm(feature_array[:, np.newaxis,:] - centroid,
                                  axis = 2)
        print(f"distance: %", distance)
        labels = np.argmin(distance, axis=1)

        # update centroid
        new_centroid = np.array([feature_array[labels == m].mean(axis=0) 
                                  for m in range(k)]) 
        if np.allclose(new_centroid, centroid):
            break
        centroid = new_centroid
    return labels

1
2


In [122]:
# print(feature_array)
# print(np.random.choice(feature_array.shape[0], 2, replace=False))
kMeansClustering(feature_array)


[[0 1 0 0 1 1 1 0 0]
 [1 0 0 0 0 0 1 0 1]
 [0 0 1 1 1 1 1 1 0]]
[[1 0 0 0 0 0 1 0 1]
 [0 1 0 0 1 1 1 0 0]]
distance: % [[2.23606798 0.        ]
 [0.         2.23606798]
 [2.64575131 2.        ]]
distance: % [[2.23606798 1.        ]
 [0.         2.23606798]
 [2.64575131 1.        ]]


array([1, 0, 1])